// <auto-generated />
using System;
using Br.Sa.Scania.TrackNTrace.Outbound.Maritimo.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Br.Sa.Scania.TrackNTrace.Outbound.Maritimo.Migrations
{
    [DbContext(typeof(OutboundTrackNTraceContext))]
    partial class OutboundTrackNTraceModelSnapshot : Microsoft.EntityFrameworkCore.Infrastructure.ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Br.Sa.Scania.TrackNTrace.Outbound.Maritimo.Models.Maritimos", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ATADestination");

                    b.Property<string>("ATDSantos");

                    b.Property<string>("BatchId");

                    b.Property<string>("Booking");

                    b.Property<string>("Chassis");

                    b.Property<string>("Container20");

                    b.Property<string>("Container40");

                    b.Property<string>("CustomerOrder");

                    b.Property<string>("ETA2Destination");

                    b.Property<string>("ETADestination");

                    b.Property<string>("ETD2Santos");

                    b.Property<string>("ETDSantos");

                    b.Property<string>("InttraNumber");

                    b.Property<string>("LastDateOutSLA");

                    b.Property<string>("Liner");

                    b.Property<string>("Market");

                    b.Property<string>("Model");

                    b.Property<string>("PDD");

                    b.Property<string>("PartPeriod");

                    b.Property<string>("PlanDelivery");

                    b.Property<string>("PlanPacking");

                    b.Property<string>("PopId");

                    b.Property<string>("PortDestination");

                    b.Property<string>("Terminal");

                    b.Property<string>("Type");

                    b.Property<string>("Vessel");

                    b.HasKey("id");

                    b.ToTable("Maritimo");
                });

            modelBuilder.Entity("Br.Sa.Scania.TrackNTrace.Outbound.Maritimo.Models.PortLocation", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Country");

                    b.Property<string>("Latitude");

                    b.Property<string>("Longitude");

                    b.Property<string>("portName");

                    b.HasKey("id");

                    b.ToTable("PortLocation");
                });

            modelBuilder.Entity("Br.Sa.Scania.TrackNTrace.Outbound.Maritimo.Models.TruckOnBoard", b =>
                {
                    b.Property<int>("TruckOnBoardId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DataDaLocalizacao");

                    b.Property<DateTime>("DataDeGravacao");

                    b.Property<string>("Latitude");

                    b.Property<int>("LicensePlate");

                    b.Property<string>("Longitude");

                    b.Property<string>("TrackNumber");

                    b.HasKey("TruckOnBoardId");

                    b.ToTable("TruckOnBoards");
                });

            modelBuilder.Entity("Br.Sa.Scania.TrackNTrace.Outbound.Maritimo.Models.VesselData", b =>
                {
                    b.Property<int>("VesselDataId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AisVesselType");

                    b.Property<string>("Capacity");

                    b.Property<string>("Flag");

                    b.Property<string>("Imo");

                    b.Property<string>("Indicative");

                    b.Property<string>("Mmsi");

                    b.Property<string>("Name");

                    b.Property<string>("State");

                    b.Property<string>("VesselSize");

                    b.Property<string>("Year");

                    b.HasKey("VesselDataId");

                    b.ToTable("VesselData");
                });

            modelBuilder.Entity("Br.Sa.Scania.TrackNTrace.Outbound.Maritimo.Models.VesselLocation", b =>
                {
                    b.Property<int>("VesselLocationId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Lat");

                    b.Property<string>("Lon");

                    b.Property<string>("Mmsi");

                    b.Property<DateTime>("SavedHourOnDB");

                    b.HasKey("VesselLocationId");

                    b.ToTable("VesselLocation");
                });
#pragma warning restore 612, 618
        }
    }
}
